exports.ATTACHMENT_RECORD_MODULE_ICE_COFEE_ID = 1;
exports.ATTACHMENT_RECORD_MODULE_HOT_COFEE_ID = 2;
exports.ATTACHMENT_RECORD_MODULE_FRUIT_JUICE_ID = 3;
exports.ATTACHMENT_RECORD_MODULE_ABOUT_ID = 4;
exports.ATTACHMENT_RECORD_MODULE_SPECIAL_ITEMS_ID = 5;